# Generated by Django 4.0.2 on 2022-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_achievement_description_alter_achievement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
