# Generated by Django 4.0.2 on 2022-02-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
