# Generated by Django 4.0.2 on 2022-02-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='enrollment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
