# Generated by Django 4.0.2 on 2022-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_member_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
    ]
